### ISSUE TITLE
Mining gas for contract deployment is failing with error

### ISSUE THREAD

**Issue by payvint** [Dirt-Road-Development/skale.js#74]
### SKALE.js Version

0.3.2

### Describe the Bug

Here is a bytecode: `60b28061000f600039806000f350fe6040516313f44d1081523360208201526040810160405260006020826024601c850173d2002000000000000000000000000000000000d27ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa15156061578081fd5b81511515606c578081fd5b7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601915081602082378035828234f580151560a6578182fd5b8082525050506014600cf3`

Tried to generate gas to deploy a contract - returned an error that Given input "NUMBER" is not a number (error from web3-utils library when it tried to calculate soliditySha3 from BN of bytecode)

### Describe Expectations

Gas to be mined

### Errors

```shell
Error: Given input "233070634920839346103616756224538253227713001046278438069785740062836890984185704696763612399300861775714551699063926876429210000203319967833941183612449599827729869954631245207337403031162157919405148544528436668532346662429306510475170031005845604619526601033266370489503704280662858916953153992954766054865346178707589501003514659584617142809885013489765440569058172309099896456649023456815165983568249203150779034186980630677036643196254548489426118096426372339" is not a number.
    at numberToHex (/Users/payvint/Documents/Blockchain/skale-deterministic-deployment-proxy/node_modules/web3-utils/lib/utils.js:243:15)
    at Object.toHex (/Users/payvint/Documents/Blockchain/skale-deterministic-deployment-proxy/node_modules/web3-utils/lib/utils.js:322:62)
    at _processSolidityEncodePackedArgs (/Users/payvint/Documents/Blockchain/skale-deterministic-deployment-proxy/node_modules/web3-utils/lib/soliditySha3.js:175:23)
    at Array.map (<anonymous>)
    at soliditySha3 (/Users/payvint/Documents/Blockchain/skale-deterministic-deployment-proxy/node_modules/web3-utils/lib/soliditySha3.js:213:24)
    at SkalePowMiner.<anonymous> (/Users/payvint/Documents/Blockchain/skale-deterministic-deployment-proxy/node_modules/@skaleproject/pow/lib/cjs/miner.js:68:87)
    at Generator.next (<anonymous>)
    at /Users/payvint/Documents/Blockchain/skale-deterministic-deployment-proxy/node_modules/@skaleproject/pow/lib/cjs/miner.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/payvint/Documents/Blockchain/skale-deterministic-deployment-proxy/node_modules/@skaleproject/pow/lib/cjs/miner.js:27:12)
```

**Comment by TheGreatAxios** [comment]
Closing as not an issue. Byes is for testing purposes only and is the gas price in bytes form if pre-defined.
